import os

NETREFER_API_ENDPOINT = os.getenv("NETREFER_API_ENDPOINT", "http://api.netrefer.com/api/list/v1")
NETREFER_API_TOKEN = os.getenv("NETREFER_API_TOKEN", "")
NETREFER_API_SUBSCRIPTION_KEY = os.getenv("NETREFER_API_SUBSCRIPTION_KEY", "")
