services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NETREFER_API_ENDPOINT=http://api.netrefer.com/api/list/v1
      - NETREFER_CLIENT_ID=
      - NETREFER_PASSWORD=
      - NETREFER_USERNAME=
      - NETREFER_API_SUBSCRIPTION_KEY=